// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagrameClase;

/************************************************************/
public class Customer extends User {
	
	private String creditCartInfo;
	
	public Customer()
	{
		
	}

	public Customer(String username, String password, String crediCartInfo)
	{
		super(username,password);
		this.creditCartInfo=crediCartInfo;
	}
};
