// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagrameClase;

/************************************************************/
/**
 * 
 */
//--------------------------------------------------------
//Code generated by Papyrus Java
//--------------------------------------------------------

//package DiagramaClase;

import java.time.LocalDate;

public class Product {

	private String productName;

	public double price;

	public int stock;

	public Product() {

	}

	LocalDate date = LocalDate.now();

	public Product(String productName) {
		this.productName = productName;
	}

	public Product(String productName, double price, int stock) {
		this.productName = productName;
		this.price = price;
		this.stock = stock;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

	public void ViewProduct() {

		System.out.println("Produsul " + this.productName + " pretul " + this.price);
	}

};
