// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagrameClase;

import java.awt.List;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;

public class ShoppingCart
{
	
	private double totalPrice;
	ArrayList<Product> cart=new ArrayList<Product>();
	private Customer customer;
	private Admin admin;

    ArrayList<Product> products=new ArrayList<Product>();
    Scanner scanner = new Scanner(System.in);
	public ShoppingCart(){
		//cart=new Product[5];
   }
	
	public ShoppingCart(int cartSize)
	{
		//cart=new Product[cartSize];
	}
	
	public ShoppingCart(Customer customer)
	{
		BuildProductCatalog();
		GetCatalogDescription();
		cart=new ArrayList<Product>();
		this.customer = customer;
	}
	
	public ShoppingCart(Admin admin)
	{
		BuildProductCatalog();
		GetCatalogDescription();
		cart=new ArrayList<Product>();
		this.admin = admin;
	}
	
	public void AddProduct(String productName){

		for(Product product : products)
	      if(product.getProductName().equals(productName))
	      {
	    	  cart.add(product);
	    	  product.stock=product.stock-1;
	      }
	}
	
	public void RemoveProduct(String productName)
	{
		for(Product product : products)
		      if(product.getProductName().equals(productName))
		      {
		    	  cart.remove(product);
		    	  product.stock=product.stock+1;
		      }
	}
	
	public void AddProductToCatalog()
	{
		System.out.println("Introduceti numele produsului nou ");
		String productName=scanner.nextLine();
		System.out.println("Introduceti pretul ");
		double price =scanner.nextDouble();
		System.out.println("Introduceti stocul  ");
		int stoc=scanner.nextInt();
		
		Product product = new Product(productName,price,stoc);
   
		products.add(product);
	}
	
	
	public void RemoveProductToCatalog(String productName)
	{
		for(Product product : products)
			if(product.getProductName().equals(productName))
			{
				products.remove(product);
     		}
	}

    public double calculateTotalPrice(ArrayList<Product> cart)
	 {
		for(int i=0; i< cart.size();i++)
		{
			totalPrice += cart.get(i).getPrice();
		}
		return totalPrice;
	 }
    
    public int getCostOfCart()
    {
        int costOfCart = 0;
        for (int i = 0; i < cart.size(); ++i)
        {
            costOfCart += cart.get(i).getPrice();
        }
        return costOfCart;
    }
  
  public void showCart()
  {
	  for(Product product : cart)
	  {
		  product.ViewProduct();
	  }
  }

public void printTotal() {

    for(int i = 0; i < cart.size(); i++)
    {
        cart.get(i).ViewProduct();
    }
    System.out.println("Total: $" + getCostOfCart());
}

 public void showAllProducts()
 {
	 for(int i=0;i<products.size();i++)
	 { System.out.println("Produsul" + products.get(i).getProductName()
				             + " pretul "+ products.get(i).getPrice()+
				             " stock "+products.get(i).getStock());
	 }
 }
 
 public void UpdateStock(String productName)
 {
	 for(int i=0;i<products.size();i++)
		 if(products.get(i).getProductName().equals(productName))
		 {
			 System.out.println("Introduceti valoarea noua a stocului ");
			 int stockNew=scanner.nextInt();
			 
			 products.get(i).stock = stockNew;
			 
		 } 
 }
 
 void BuildProductCatalog()
 {
     Product meat1 = new Product("Ship", 30, 200);
     Product meat2 = new Product("Cow", 45, 300);

     Product seafood1 = new Product("shrimp", 100, 400);
     Product seafood2 = new Product("Octopus", 200, 500);

     Product fish1 = new Product("Salmon", 70, 350);
     Product fish2 = new Product("Mackerel", 300, 100);

     products.add(meat1);
     products.add(meat2);
     products.add(seafood1);
     products.add(seafood2);
     products.add(fish1);
     products.add(fish2);
 }

public void GetCatalogDescription()
{
   for(int i=0;i<products.size();i++)
       products.get(i).ViewProduct();
}


}