// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DiagrameClase;

//--------------------------------------------------------
//Code generated by Papyrus Java
//--------------------------------------------------------

//package DiagramaClase;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

public class User {

	private String Username;
	
	private String Password;

 private String email;
	
	private String contactNumber;
	
	
	public User()
	{
		
	}
	public User(String Username,String Password)
	{
		this.Username =Username;
		this.Password=Password;
	}
	
	public String getUsername()
	{
		return this.Username;
	}
	
	public void setUsername(String Username)
	{
		this.Username=Username;
	}
	
	public String getPassword()
	{
		return this.Password;
	}
	
	public void setPassword(String Password)
	{
		this.Password=Password;
	}

	
	public String getEmail()
	{
		return this.email;
	}
	
	public void setEmail(String email)
	{
		this.email = email;
	}
	
	public String getContactNumber()
	{
		return this.contactNumber;
	}
	
	public void setContactNumber(String contactNumber)
	{
		this.contactNumber=contactNumber;
	}
	

		public void read_user_csv(String filename)
 {
     String line = "";
     String splitBy = ",";

     try {
         BufferedReader br = new BufferedReader(new FileReader(filename));

         while ((line = br.readLine()) != null) {
             String[] users = line.split(splitBy);
             System.out.println
                     ("Username = " + users[0] 
                     + " Password = " + users[1]
                     + " Email= " + users[2]
                     + " Contact Number = " + users[3]
                    );
         }
     } catch (IOException var6) {
         var6.printStackTrace();
     }
 }
 public void create_account(String filename,String username, String email,
                            String contact_number, String password)
 {
     PrintWriter csvWriter;
     try {
         /*1. declare stringBuffer*/
         StringBuffer oneLineStringBuffer = new StringBuffer();

         File file = new File(filename);
         if (!file.exists()) {
             file = new File(filename);
         }
         csvWriter = new PrintWriter(new FileWriter(file, true));

         oneLineStringBuffer.append("\n");
         oneLineStringBuffer.append(username);
         oneLineStringBuffer.append(",");
         oneLineStringBuffer.append(email);
         oneLineStringBuffer.append(",");
         oneLineStringBuffer.append(contact_number);
         oneLineStringBuffer.append(",");
         oneLineStringBuffer.append(password);

         csvWriter.print(oneLineStringBuffer);

         csvWriter.close();

     } catch (Exception e) {
         e.printStackTrace();
     }
 }
 public void login_user(String filename,String username,String password)
 {
     String line = "";
     String splitBy = ",";

     try {
         BufferedReader br = new BufferedReader(new FileReader(filename));

         while ((line = br.readLine()) != null) {
             String[] users = line.split(splitBy);
             if((users[0].equals(username)) &&(users[1].equals(password)))
             {
                 System.out.println("Logare reusita");
             }

         }
     } catch (IOException var6) {
         var6.printStackTrace();
     }
 }
}
